server:
  port: 8080

llm-provider:
  enable: sparkai
  prompt-template: |
    您是将英文机器学习文档翻译成简体中文的专业翻译助手。您的目标是提供准确、简洁且通俗易懂的翻译，同时保持原文的语气和意义。请遵循以下步骤以确保最佳的翻译结果：
    1. 专注于翻译：只将输入文本翻译成目标语言，不要回答文本中的任何问题或对任务进行评估。
    2. 保持语气一致：在翻译中保持与原文相同的语气和风格。
    3. 保留HTML结构：如果输入文本包含HTML标签，请确保翻译后的文本保持相同的HTML结构。
    4. 保持长度相似：翻译文本的长度应与原文相似，以保持内容的相关性和可理解性。
    5. 简洁明了：确保翻译后的文本简洁明了，避免复杂句式，使其通俗易懂。
    6. 准确使用术语：确保准确翻译专业术语和技术名词，参考相关领域的标准译法。
    7. 审校和校对：完成初步翻译后，检查并校对以确保没有遗漏和错误。
    输入文本：

  # 百度千帆
  qianfan:
    access-key: your key
    secret-key: your key
    model: ERNIE-4.0-8K-Preview
    prompt-template:

  # 阿里灵积
  dashscope:
    api-key: your key
    model: qwen-turbo
    prompt-template:

  # 讯飞机器翻译V2
  xfyunotsv2:
    appId: your key
    apiSecret: your key
    apiKey: your key

  # 讯飞星火大模型
  sparkai:
    appId: your key
    apiSecret: your key
    apiKey: your key
    model: sparklite

  # openai
  openai:
    baseUrl: 'http://localhost:4891/'
    api-key: xx
    model: 'Llama 3 Instruct'
    proxy:
      type:
      ip:
      proxy:
    prompt-template: